# SPDX-FileCopyrightText: 2026 VAAET Contributors
# SPDX-License-Identifier: AGPL-3.0-only
"""Create namespaced PostgreSQL storage and append-only HITL.

Revision ID: 20260804_0001
Revises: None
Create Date: 2026-08-04
"""

from alembic import op

revision = "20260804_0001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute("CREATE SCHEMA IF NOT EXISTS vaaet_raw")
    op.execute("CREATE SCHEMA IF NOT EXISTS vaaet_ml")
    op.execute("CREATE SCHEMA IF NOT EXISTS vaaet_feedback")

    op.execute(
        """
        DO $$ BEGIN
          IF to_regclass('vaaet_raw.traffic_data') IS NULL
             AND to_regclass('public.traffic_data') IS NOT NULL
             AND (SELECT relkind FROM pg_class WHERE oid = to_regclass('public.traffic_data')) = 'r'
          THEN ALTER TABLE public.traffic_data SET SCHEMA vaaet_raw; END IF;

          IF to_regclass('vaaet_ml.telemetry_features') IS NULL
             AND to_regclass('public.telemetry_raw') IS NOT NULL
             AND (SELECT relkind FROM pg_class WHERE oid = to_regclass('public.telemetry_raw')) = 'r'
          THEN
            ALTER TABLE public.telemetry_raw SET SCHEMA vaaet_ml;
            ALTER TABLE vaaet_ml.telemetry_raw RENAME TO telemetry_features;
          END IF;

          IF to_regclass('vaaet_ml.traffic_predictions') IS NULL
             AND to_regclass('public.traffic_classifications') IS NOT NULL
             AND (SELECT relkind FROM pg_class WHERE oid = to_regclass('public.traffic_classifications')) = 'r'
          THEN
            ALTER TABLE public.traffic_classifications SET SCHEMA vaaet_ml;
            ALTER TABLE vaaet_ml.traffic_classifications RENAME TO traffic_predictions;
          END IF;
        END $$;
        """
    )

    op.execute(
        """
        CREATE TABLE IF NOT EXISTS vaaet_raw.traffic_data (
          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          pipeline_run_id UUID NOT NULL,
          clip_id TEXT NOT NULL,
          record_time TIMESTAMPTZ NOT NULL,
          avg_speed NUMERIC(8,2) NOT NULL CHECK (avg_speed >= 0),
          count_car INTEGER NOT NULL CHECK (count_car >= 0),
          count_truck INTEGER NOT NULL CHECK (count_truck >= 0),
          count_bus INTEGER NOT NULL CHECK (count_bus >= 0),
          count_motorcycle INTEGER NOT NULL CHECK (count_motorcycle >= 0),
          count_bicycle INTEGER NOT NULL CHECK (count_bicycle >= 0),
          total_vehicles INTEGER NOT NULL CHECK (total_vehicles >= 0),
          near_zero_motion_count INTEGER CHECK (near_zero_motion_count >= 0),
          stationary_confirmed_count INTEGER CHECK (stationary_confirmed_count >= 0),
          rejected_speed_count INTEGER CHECK (rejected_speed_count >= 0),
          recovered_track_count INTEGER CHECK (recovered_track_count >= 0),
          speed_sample_count INTEGER CHECK (speed_sample_count >= 0),
          speed_measurement_quality NUMERIC(8,4) CHECK (speed_measurement_quality BETWEEN 0 AND 1),
          optical_flow_tracking_ratio NUMERIC(8,4) CHECK (optical_flow_tracking_ratio BETWEEN 0 AND 1),
          telemetry_schema_version TEXT,
          created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
          UNIQUE (clip_id, record_time)
        )
        """
    )
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS vaaet_ml.telemetry_features (
          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          source_record_id BIGINT REFERENCES vaaet_raw.traffic_data(id) ON DELETE RESTRICT,
          pipeline_run_id UUID NOT NULL,
          clip_id TEXT NOT NULL,
          record_time TIMESTAMPTZ NOT NULL,
          feature_schema_version TEXT NOT NULL,
          avg_speed NUMERIC(8,2), total_vehicles INTEGER,
          count_car INTEGER, count_truck INTEGER, count_bus INTEGER,
          count_motorcycle INTEGER, count_bicycle INTEGER,
          heavy_vehicle_ratio NUMERIC(8,4) CHECK (heavy_vehicle_ratio BETWEEN 0 AND 1),
          delta_speed NUMERIC(8,2), delta_count INTEGER,
          transition_flag SMALLINT NOT NULL DEFAULT 0 CHECK (transition_flag IN (0,1)),
          speed_variance NUMERIC(8,4), cumulative_delta_speed NUMERIC(8,2),
          low_speed_persistence NUMERIC(8,4),
          speed_measurement_quality NUMERIC(8,4) CHECK (speed_measurement_quality BETWEEN 0 AND 1),
          optical_flow_tracking_ratio NUMERIC(8,4) CHECK (optical_flow_tracking_ratio BETWEEN 0 AND 1),
          near_zero_motion_ratio NUMERIC(8,4) CHECK (near_zero_motion_ratio BETWEEN 0 AND 1),
          stationary_confirmed_ratio NUMERIC(8,4) CHECK (stationary_confirmed_ratio BETWEEN 0 AND 1),
          near_zero_motion_count INTEGER, stationary_confirmed_count INTEGER,
          rejected_speed_count INTEGER, recovered_track_count INTEGER,
          speed_sample_count INTEGER, telemetry_schema_version TEXT,
          data_origin TEXT NOT NULL DEFAULT 'real',
          synthetic_scenario TEXT NOT NULL DEFAULT 'observed',
          hour_of_day SMALLINT CHECK (hour_of_day BETWEEN 0 AND 23),
          weather_condition SMALLINT,
          created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
          UNIQUE (clip_id, record_time, feature_schema_version)
        )
        """
    )
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS vaaet_ml.traffic_predictions (
          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          telemetry_feature_id BIGINT NOT NULL REFERENCES vaaet_ml.telemetry_features(id) ON DELETE CASCADE,
          pipeline_run_id UUID NOT NULL,
          classified_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
          traffic_state SMALLINT NOT NULL CHECK (traffic_state BETWEEN 0 AND 2),
          state_label TEXT NOT NULL,
          confidence NUMERIC(8,4) NOT NULL CHECK (confidence BETWEEN 0 AND 1),
          model_version TEXT NOT NULL,
          model_traffic_state SMALLINT CHECK (model_traffic_state BETWEEN 0 AND 2),
          model_state_label TEXT,
          model_confidence NUMERIC(8,4) CHECK (model_confidence BETWEEN 0 AND 1),
          probability_margin NUMERIC(8,4) CHECK (probability_margin BETWEEN 0 AND 1),
          decision_abstained BOOLEAN NOT NULL DEFAULT FALSE,
          measurement_reliable BOOLEAN,
          accident_rule_triggered BOOLEAN NOT NULL DEFAULT FALSE,
          accident_alert_started BOOLEAN NOT NULL DEFAULT FALSE,
          accident_evidence_score NUMERIC(8,4) CHECK (accident_evidence_score BETWEEN 0 AND 1),
          UNIQUE (telemetry_feature_id, model_version)
        )
        """
    )

    # Bring legacy tables to the v2 relational contract before moving HITL rows.
    for statement in (
        "ALTER TABLE vaaet_raw.traffic_data ADD COLUMN IF NOT EXISTS pipeline_run_id UUID",
        "ALTER TABLE vaaet_raw.traffic_data ADD COLUMN IF NOT EXISTS near_zero_motion_count INTEGER",
        "ALTER TABLE vaaet_raw.traffic_data ADD COLUMN IF NOT EXISTS stationary_confirmed_count INTEGER",
        "ALTER TABLE vaaet_raw.traffic_data ADD COLUMN IF NOT EXISTS rejected_speed_count INTEGER",
        "ALTER TABLE vaaet_raw.traffic_data ADD COLUMN IF NOT EXISTS recovered_track_count INTEGER",
        "ALTER TABLE vaaet_raw.traffic_data ADD COLUMN IF NOT EXISTS speed_sample_count INTEGER",
        "ALTER TABLE vaaet_raw.traffic_data ADD COLUMN IF NOT EXISTS speed_measurement_quality NUMERIC(8,4)",
        "ALTER TABLE vaaet_raw.traffic_data ADD COLUMN IF NOT EXISTS optical_flow_tracking_ratio NUMERIC(8,4)",
        "ALTER TABLE vaaet_raw.traffic_data ADD COLUMN IF NOT EXISTS telemetry_schema_version TEXT",
        "ALTER TABLE vaaet_raw.traffic_data ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP",
        "ALTER TABLE vaaet_ml.telemetry_features ADD COLUMN IF NOT EXISTS pipeline_run_id UUID",
        "ALTER TABLE vaaet_ml.telemetry_features ADD COLUMN IF NOT EXISTS feature_schema_version TEXT",
        "ALTER TABLE vaaet_ml.telemetry_features ADD COLUMN IF NOT EXISTS speed_measurement_quality NUMERIC(8,4)",
        "ALTER TABLE vaaet_ml.telemetry_features ADD COLUMN IF NOT EXISTS optical_flow_tracking_ratio NUMERIC(8,4)",
        "ALTER TABLE vaaet_ml.telemetry_features ADD COLUMN IF NOT EXISTS near_zero_motion_ratio NUMERIC(8,4)",
        "ALTER TABLE vaaet_ml.telemetry_features ADD COLUMN IF NOT EXISTS stationary_confirmed_ratio NUMERIC(8,4)",
        "ALTER TABLE vaaet_ml.telemetry_features ADD COLUMN IF NOT EXISTS near_zero_motion_count INTEGER",
        "ALTER TABLE vaaet_ml.telemetry_features ADD COLUMN IF NOT EXISTS stationary_confirmed_count INTEGER",
        "ALTER TABLE vaaet_ml.telemetry_features ADD COLUMN IF NOT EXISTS rejected_speed_count INTEGER",
        "ALTER TABLE vaaet_ml.telemetry_features ADD COLUMN IF NOT EXISTS recovered_track_count INTEGER",
        "ALTER TABLE vaaet_ml.telemetry_features ADD COLUMN IF NOT EXISTS speed_sample_count INTEGER",
        "ALTER TABLE vaaet_ml.telemetry_features ADD COLUMN IF NOT EXISTS telemetry_schema_version TEXT",
        "ALTER TABLE vaaet_ml.telemetry_features ADD COLUMN IF NOT EXISTS data_origin TEXT DEFAULT 'real'",
        "ALTER TABLE vaaet_ml.telemetry_features ADD COLUMN IF NOT EXISTS synthetic_scenario TEXT DEFAULT 'observed'",
        "ALTER TABLE vaaet_ml.telemetry_features ADD COLUMN IF NOT EXISTS hour_of_day SMALLINT",
        "ALTER TABLE vaaet_ml.telemetry_features ADD COLUMN IF NOT EXISTS weather_condition SMALLINT",
        "ALTER TABLE vaaet_ml.telemetry_features ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP",
        "ALTER TABLE vaaet_ml.traffic_predictions ADD COLUMN IF NOT EXISTS pipeline_run_id UUID",
        "ALTER TABLE vaaet_ml.traffic_predictions ADD COLUMN IF NOT EXISTS model_traffic_state SMALLINT",
        "ALTER TABLE vaaet_ml.traffic_predictions ADD COLUMN IF NOT EXISTS model_state_label TEXT",
        "ALTER TABLE vaaet_ml.traffic_predictions ADD COLUMN IF NOT EXISTS model_confidence NUMERIC(8,4)",
        "ALTER TABLE vaaet_ml.traffic_predictions ADD COLUMN IF NOT EXISTS probability_margin NUMERIC(8,4)",
        "ALTER TABLE vaaet_ml.traffic_predictions ADD COLUMN IF NOT EXISTS decision_abstained BOOLEAN DEFAULT FALSE",
        "ALTER TABLE vaaet_ml.traffic_predictions ADD COLUMN IF NOT EXISTS measurement_reliable BOOLEAN",
        "ALTER TABLE vaaet_ml.traffic_predictions ADD COLUMN IF NOT EXISTS accident_rule_triggered BOOLEAN DEFAULT FALSE",
        "ALTER TABLE vaaet_ml.traffic_predictions ADD COLUMN IF NOT EXISTS accident_alert_started BOOLEAN DEFAULT FALSE",
        "ALTER TABLE vaaet_ml.traffic_predictions ADD COLUMN IF NOT EXISTS accident_evidence_score NUMERIC(8,4)",
    ):
        op.execute(statement)

    op.execute(
        """
        DO $$ BEGIN
          IF EXISTS (
            SELECT 1 FROM information_schema.columns
            WHERE table_schema='vaaet_ml' AND table_name='traffic_predictions'
              AND column_name='telemetry_id'
          ) AND NOT EXISTS (
            SELECT 1 FROM information_schema.columns
            WHERE table_schema='vaaet_ml' AND table_name='traffic_predictions'
              AND column_name='telemetry_feature_id'
          ) THEN
            ALTER TABLE vaaet_ml.traffic_predictions
              RENAME COLUMN telemetry_id TO telemetry_feature_id;
          END IF;
        END $$;
        """
    )

    op.execute(
        "UPDATE vaaet_raw.traffic_data SET pipeline_run_id = md5('raw-' || id::text)::uuid WHERE pipeline_run_id IS NULL"
    )
    op.execute(
        "UPDATE vaaet_ml.telemetry_features SET pipeline_run_id = md5('feature-' || id::text)::uuid WHERE pipeline_run_id IS NULL"
    )
    op.execute(
        "UPDATE vaaet_ml.telemetry_features SET feature_schema_version = 'traffic-features-v2' WHERE feature_schema_version IS NULL"
    )
    op.execute("UPDATE vaaet_ml.telemetry_features SET data_origin = 'real' WHERE data_origin IS NULL")
    op.execute(
        "UPDATE vaaet_ml.telemetry_features SET synthetic_scenario = 'observed' "
        "WHERE synthetic_scenario IS NULL"
    )
    op.execute(
        "UPDATE vaaet_ml.traffic_predictions SET pipeline_run_id = md5('prediction-' || id::text)::uuid WHERE pipeline_run_id IS NULL"
    )
    op.execute(
        "UPDATE vaaet_ml.traffic_predictions SET decision_abstained = COALESCE(decision_abstained, FALSE), "
        "accident_rule_triggered = COALESCE(accident_rule_triggered, FALSE), "
        "accident_alert_started = COALESCE(accident_alert_started, FALSE) "
        "WHERE decision_abstained IS NULL OR accident_rule_triggered IS NULL "
        "OR accident_alert_started IS NULL"
    )
    op.execute("ALTER TABLE vaaet_raw.traffic_data ALTER COLUMN pipeline_run_id SET NOT NULL")
    op.execute("ALTER TABLE vaaet_ml.telemetry_features ALTER COLUMN pipeline_run_id SET NOT NULL")
    op.execute("ALTER TABLE vaaet_ml.telemetry_features ALTER COLUMN feature_schema_version SET NOT NULL")
    op.execute("ALTER TABLE vaaet_ml.telemetry_features ALTER COLUMN data_origin SET NOT NULL")
    op.execute("ALTER TABLE vaaet_ml.telemetry_features ALTER COLUMN synthetic_scenario SET NOT NULL")
    op.execute("ALTER TABLE vaaet_ml.traffic_predictions ALTER COLUMN pipeline_run_id SET NOT NULL")
    op.execute("ALTER TABLE vaaet_ml.traffic_predictions ALTER COLUMN decision_abstained SET NOT NULL")
    op.execute("ALTER TABLE vaaet_ml.traffic_predictions ALTER COLUMN accident_rule_triggered SET NOT NULL")
    op.execute("ALTER TABLE vaaet_ml.traffic_predictions ALTER COLUMN accident_alert_started SET NOT NULL")

    op.execute(
        """
        DO $$ DECLARE item RECORD;
        BEGIN
          FOR item IN SELECT * FROM (VALUES
            ('vaaet_raw','traffic_data','record_time'),
            ('vaaet_ml','telemetry_features','record_time'),
            ('vaaet_ml','traffic_predictions','classified_at'),
            ('vaaet_ml','traffic_predictions','validated_at')
          ) AS v(schema_name, table_name, column_name)
          LOOP
            IF EXISTS (
              SELECT 1 FROM information_schema.columns
              WHERE table_schema=item.schema_name AND table_name=item.table_name
                AND column_name=item.column_name AND data_type='timestamp without time zone'
            ) THEN
              EXECUTE format(
                'ALTER TABLE %I.%I ALTER COLUMN %I TYPE TIMESTAMPTZ USING %I AT TIME ZONE %L',
                item.schema_name, item.table_name, item.column_name, item.column_name,
                'America/Argentina/Buenos_Aires'
              );
            END IF;
          END LOOP;
        END $$;
        """
    )

    op.execute(
        """
        CREATE TABLE IF NOT EXISTS vaaet_feedback.human_validations (
          id UUID PRIMARY KEY,
          prediction_id BIGINT NOT NULL REFERENCES vaaet_ml.traffic_predictions(id) ON DELETE RESTRICT,
          validated_state SMALLINT NOT NULL CHECK (validated_state BETWEEN 0 AND 3),
          reviewer_id TEXT NOT NULL CHECK (length(trim(reviewer_id)) > 0),
          reviewed_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
          notes TEXT,
          review_source TEXT NOT NULL DEFAULT 'colab',
          incident_context_reviewed BOOLEAN NOT NULL DEFAULT FALSE,
          supersedes_validation_id UUID REFERENCES vaaet_feedback.human_validations(id),
          CHECK (
            validated_state <> 3 OR
            (incident_context_reviewed AND notes IS NOT NULL AND length(trim(notes)) > 0)
          )
        )
        """
    )

    op.execute(
        """
        DO $$ BEGIN
          IF EXISTS (
            SELECT 1 FROM information_schema.columns
            WHERE table_schema='vaaet_ml' AND table_name='traffic_predictions'
              AND column_name='is_human_validated'
          ) THEN
            INSERT INTO vaaet_feedback.human_validations (
              id, prediction_id, validated_state, reviewer_id, reviewed_at, notes,
              review_source, incident_context_reviewed
            )
            SELECT md5('legacy-validation-' || id::text)::uuid,
                   id, COALESCE(human_override_state, traffic_state), 'legacy-migration',
                   COALESCE(validated_at, classified_at), 'Migrated from VAAET 4.0 HITL fields',
                   'legacy-migration', COALESCE(human_override_state, traffic_state) = 3
            FROM vaaet_ml.traffic_predictions
            WHERE is_human_validated IS TRUE
            ON CONFLICT (id) DO NOTHING;

            UPDATE vaaet_ml.traffic_predictions
            SET traffic_state = COALESCE(model_traffic_state, 2),
                state_label = CASE COALESCE(model_traffic_state, 2)
                  WHEN 0 THEN 'Normal' WHEN 1 THEN 'Reduced' ELSE 'Congested' END
            WHERE traffic_state = 3;

            ALTER TABLE vaaet_ml.traffic_predictions
              DROP COLUMN IF EXISTS is_human_validated,
              DROP COLUMN IF EXISTS human_override_state,
              DROP COLUMN IF EXISTS validated_at,
              DROP COLUMN IF EXISTS accident_gate_applied;
          END IF;
        END $$;
        """
    )

    op.execute(
        """
        CREATE OR REPLACE VIEW vaaet_feedback.effective_human_labels AS
        SELECT f.*, p.id AS prediction_id, p.model_version,
               v.validated_state AS traffic_state,
               TRUE AS is_human_validated,
               v.reviewer_id, v.reviewed_at, v.notes
        FROM vaaet_ml.telemetry_features f
        JOIN vaaet_ml.traffic_predictions p ON p.telemetry_feature_id = f.id
        JOIN LATERAL (
          SELECT hv.* FROM vaaet_feedback.human_validations hv
          WHERE hv.prediction_id = p.id
          ORDER BY hv.reviewed_at DESC, hv.id DESC LIMIT 1
        ) v ON TRUE
        """
    )
    op.execute(
        """
        CREATE OR REPLACE VIEW vaaet_feedback.review_queue AS
        SELECT p.id AS prediction_id, p.pipeline_run_id, f.clip_id, f.record_time,
               p.traffic_state, p.state_label, p.confidence, p.model_version,
               p.probability_margin, p.decision_abstained, p.measurement_reliable,
               p.accident_rule_triggered, p.accident_alert_started,
               p.accident_evidence_score,
               v.id AS latest_validation_id,
               v.validated_state AS current_validated_state,
               v.reviewer_id AS current_reviewer_id,
               v.reviewed_at AS current_reviewed_at
        FROM vaaet_ml.traffic_predictions p
        JOIN vaaet_ml.telemetry_features f ON f.id = p.telemetry_feature_id
        LEFT JOIN LATERAL (
          SELECT hv.* FROM vaaet_feedback.human_validations hv
          WHERE hv.prediction_id = p.id
          ORDER BY hv.reviewed_at DESC, hv.id DESC LIMIT 1
        ) v ON TRUE
        """
    )

    op.execute("DROP VIEW IF EXISTS public.traffic_data CASCADE")
    op.execute("DROP VIEW IF EXISTS public.telemetry_raw CASCADE")
    op.execute("DROP VIEW IF EXISTS public.traffic_classifications CASCADE")
    op.execute("CREATE VIEW public.traffic_data AS SELECT * FROM vaaet_raw.traffic_data")
    op.execute("CREATE VIEW public.telemetry_raw AS SELECT * FROM vaaet_ml.telemetry_features")
    op.execute(
        """
        CREATE VIEW public.traffic_classifications AS
        SELECT p.id, p.telemetry_feature_id AS telemetry_id, p.classified_at,
               COALESCE(v.validated_state, p.traffic_state) AS traffic_state,
               CASE COALESCE(v.validated_state, p.traffic_state)
                 WHEN 0 THEN 'Normal' WHEN 1 THEN 'Reduced'
                 WHEN 2 THEN 'Congested' ELSE 'Accident' END AS state_label,
               p.confidence, p.model_version, p.model_traffic_state,
               p.model_state_label, p.model_confidence, p.probability_margin,
               p.decision_abstained, p.measurement_reliable,
               p.accident_rule_triggered, p.accident_alert_started,
               p.accident_evidence_score,
               (v.id IS NOT NULL) AS is_human_validated,
               v.validated_state AS human_override_state,
               v.reviewed_at AS validated_at
        FROM vaaet_ml.traffic_predictions p
        LEFT JOIN LATERAL (
          SELECT hv.* FROM vaaet_feedback.human_validations hv
          WHERE hv.prediction_id = p.id
          ORDER BY hv.reviewed_at DESC, hv.id DESC LIMIT 1
        ) v ON TRUE
        """
    )

    op.execute(
        "ALTER TABLE vaaet_raw.traffic_data ADD CONSTRAINT ck_raw_base_nonnegative "
        "CHECK (avg_speed >= 0 AND count_car >= 0 AND count_truck >= 0 "
        "AND count_bus >= 0 AND count_motorcycle >= 0 AND count_bicycle >= 0 "
        "AND total_vehicles >= 0)"
    )
    op.execute(
        "ALTER TABLE vaaet_raw.traffic_data ADD CONSTRAINT ck_raw_v2_counts_nonnegative "
        "CHECK (near_zero_motion_count >= 0 AND stationary_confirmed_count >= 0 "
        "AND rejected_speed_count >= 0 AND recovered_track_count >= 0 "
        "AND speed_sample_count >= 0)"
    )
    op.execute(
        "ALTER TABLE vaaet_raw.traffic_data ADD CONSTRAINT ck_raw_v2_ratios "
        "CHECK (speed_measurement_quality BETWEEN 0 AND 1 "
        "AND optical_flow_tracking_ratio BETWEEN 0 AND 1)"
    )
    op.execute(
        "ALTER TABLE vaaet_ml.telemetry_features ADD CONSTRAINT ck_features_base_values "
        "CHECK (avg_speed >= 0 AND total_vehicles >= 0 AND count_car >= 0 "
        "AND count_truck >= 0 AND count_bus >= 0 AND count_motorcycle >= 0 "
        "AND count_bicycle >= 0 AND speed_variance >= 0 "
        "AND hour_of_day BETWEEN 0 AND 23 AND weather_condition IN (0,1))"
    )
    op.execute(
        "ALTER TABLE vaaet_ml.telemetry_features ADD CONSTRAINT ck_features_quality_ratios "
        "CHECK (heavy_vehicle_ratio BETWEEN 0 AND 1 "
        "AND speed_measurement_quality BETWEEN 0 AND 1 "
        "AND optical_flow_tracking_ratio BETWEEN 0 AND 1 "
        "AND near_zero_motion_ratio BETWEEN 0 AND 1 "
        "AND stationary_confirmed_ratio BETWEEN 0 AND 1)"
    )
    op.execute(
        "ALTER TABLE vaaet_ml.telemetry_features ADD CONSTRAINT ck_features_counts_nonnegative "
        "CHECK (near_zero_motion_count >= 0 AND stationary_confirmed_count >= 0 "
        "AND rejected_speed_count >= 0 AND recovered_track_count >= 0 "
        "AND speed_sample_count >= 0)"
    )
    op.execute(
        "ALTER TABLE vaaet_ml.traffic_predictions ADD CONSTRAINT ck_predictions_ratios "
        "CHECK (confidence BETWEEN 0 AND 1 AND model_confidence BETWEEN 0 AND 1 "
        "AND probability_margin BETWEEN 0 AND 1 "
        "AND accident_evidence_score BETWEEN 0 AND 1)"
    )

    op.execute("CREATE INDEX IF NOT EXISTS idx_raw_clip_time ON vaaet_raw.traffic_data (clip_id, record_time)")
    op.execute("CREATE INDEX IF NOT EXISTS idx_features_clip_time ON vaaet_ml.telemetry_features (clip_id, record_time)")
    op.execute("CREATE INDEX IF NOT EXISTS idx_predictions_run ON vaaet_ml.traffic_predictions (pipeline_run_id)")
    op.execute("CREATE INDEX IF NOT EXISTS idx_validations_prediction_time ON vaaet_feedback.human_validations (prediction_id, reviewed_at DESC)")
    op.execute(
        "CREATE UNIQUE INDEX IF NOT EXISTS uq_features_clip_time_schema "
        "ON vaaet_ml.telemetry_features (clip_id, record_time, feature_schema_version)"
    )
    op.execute(
        "CREATE UNIQUE INDEX IF NOT EXISTS uq_predictions_feature_model "
        "ON vaaet_ml.traffic_predictions (telemetry_feature_id, model_version)"
    )
    op.execute(
        "ALTER TABLE vaaet_ml.traffic_predictions DROP CONSTRAINT IF EXISTS "
        "traffic_classifications_traffic_state_check"
    )
    op.execute(
        "ALTER TABLE vaaet_ml.traffic_predictions DROP CONSTRAINT IF EXISTS "
        "traffic_predictions_traffic_state_check"
    )
    op.execute(
        "ALTER TABLE vaaet_ml.traffic_predictions ADD CONSTRAINT "
        "ck_predictions_stable_state CHECK (traffic_state BETWEEN 0 AND 2)"
    )


def downgrade() -> None:
    raise RuntimeError(
        "The vaaet-db-v2 migration is intentionally irreversible because it separates "
        "append-only human ground truth. Restore a pre-migration backup if rollback is required."
    )
